apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-server-deployment
  labels:
    app: music-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-server
  template:
    metadata:
      labels:
        app: music-server
    spec:
      containers:
      - name: music-server
        image: masteradios123/music-streaming-music-server
        envFrom:
          - configMapRef:
              name: music-server-config
        ports:
        - containerPort: 4002
