server:
  port:
    4002

spring:
  application:
    name: music-streaming

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      spring.json.add.type.headers: false

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}

  servlet:
    multipart:
      enabled: true





