
server:
  port:
    4001

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASS}


jwt:
  secret: NagmaKoiGungunaneKaMausamAayaHaiPalkonPeKhwaabSajaaneKaMausamAayaHai


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

