server:
  port:
    4000


auth:
  service:
    url : ${AUTH_SERVICE_URL}

spring:
  application:
    name: api-gateway


  cloud:
    gateway:

      server:



        webflux:


          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: ${FRONT_END_URL}
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders: "*"
                allowCredentials: true

          routes:
            - id: MUSIC-SERVICE
              uri: ${MUSIC_SERVICE_URL}
              predicates:
                - Path=/music/**
              filters:
                - JwtValidation

            - id: AUTH-SERVICE
              uri: ${AUTH_SERVICE_URL}
              predicates:
                - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

