apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-server-config
  labels:
    app: auth-server
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"
  POSTGRES_DB_NAME: musicdb
  POSTGRES_USERNAME: postgres
  POSTGRES_PASS: postgres