apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  labels:
    app: auth-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: masteradios123/music-streaming-auth-server
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
        - containerPort: 4001
