apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-server-config
  labels:
    app: gateway-server
data:
  AUTH_SERVICE_URL: http://auth-service:4001
  FRONT_END_URL: http://localhost:5173
  MUSIC_SERVICE_URL: http://music-service:4002